### ISSUE TITLE
AWS SIGV4 signature mismatch with "binary" payload

### ISSUE THREAD

**Issue by sky-wang** [badslug/Paw-AWSSignature4DynamicValue#21] opened 2018-04-25 03:32 UTC
When the body is binary file, there is error "The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.". It is the same as with postman: https://github.com/postmanlabs/postman-app-support/issues/3232

Is this a AWS bug or the method for calculating signature for binary type is wrong?

**Comment by badslug** [comment] 2018-04-25 05:32
The signature spec doesn't mention binary payloads from what I recall. What API do you use with binary data?

**Comment by sky-wang** [comment] 2018-04-25 05:40
@badslug AWS API Gateway(execute-api)

**Comment by badslug** [comment] 2018-04-25 06:00
According to the docs you have to use `application/json` bodies for calling the API Gateway according to https://docs.aws.amazon.com/apigateway/api-reference/making-http-requests/

Is that true? Can you point me to where they document binary bodies. Every example is with a `application/json`

**Comment by sky-wang** [comment] 2018-04-25 06:16
Here is the link https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-content-encodings-examples-image-s3.html
I'm setting the Content-Type as image/png, it works fine if I turn off the auth. Also the signature is correct for GET, but not for PUT.

**Comment by badslug** [comment] 2018-04-25 06:35
Ah, I see. I'll try to take a look tomorrow. I'm guessing it will require some assistance from AWS. We are following the published spec so I'm guessing it's some  trick with certain headers it wants in the signature that we don't realize should be in there. I'll try to remember to update the postman issue if we figure it out so we can avoid duplicate work.

**Comment by badslug** [comment] 2018-04-26 06:29
@sky-wang when you get the error message does it include more text? I'm seeing in the forums that the error message should include another couple lines that starts with "The canonical string for this request should have been..." and then the actual canonical string. I'm pretty sure I am using the wrong canonical string and the error message should include the string we should be using.

**Comment by badslug** [comment] 2018-04-26 06:30
https://forums.aws.amazon.com/thread.jspa?messageID=780467&#780467

**Comment by sky-wang** [comment] 2018-04-26 06:37
No, it does not contain more text. This is all I get:
`{"message":"The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."}`

**Comment by badslug** [comment] 2018-04-30 22:46
I've reviewed the code and the docs and have run into a dead end. It's strange, the docs say we should get the canonical string to sign in the error message:

https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

Unfortunately, without knowing what AWS expects to sign, it's virtually impossible to figure out what the issue is. 

If you wanted to send the complete raw request and response I can try to see if there is anything interesting that may provide some clues (redact any sensitive information but leave all the fields present).

Sorry

**Comment by Shambler13** [comment] 2018-05-03 17:03
Hello, 
I'm facing a similar problem, but with the GET method.

Always signature mismatch.. should i add something to postman to calculate well or i dont know?

I have the same result, when i let postman calculate the signature, or i calculate it by myself using their example.

I removed the extra codes of token and cach control generated automatically by POSTMAN and i still have signature mismatch.. any help ?

**Comment by badslug** [comment] 2018-05-05 00:37
Hi @Shambler13 
 
I think you should add your request to the postman project. This project is far an extension to the Paw tool from Lucky Marmot.

**Comment by badslug** [comment] 2020-10-22 02:46
Closing due to lack of information. Please re-open or create a new issue if you have problems.

**Closed as completed by badslug** 2020-10-22 02:46 UTC
