### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by frsechet** [badslug/Paw-AWSSignature4DynamicValue#23] opened 2019-06-04 08:38 UTC
I'm getting the following error when using this plugin on a `@connections` command (for the new apigatewaymanagement API to use with websockets):

```
The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

The Canonical String for this request should have been
'POST
/dev/%2540connections/asnFYeJtCGYCEZQ%253D

host:xxxxxxxx.execute-api.eu-west-3.amazonaws.com
x-amz-date:20190603T094447Z

host;x-amz-date
df305547ae4525026fcef410e7e0336c24599629cfe05478c3222XXXXXXXXXX'

The String-to-Sign should have been
'AWS4-HMAC-SHA256
20190603T094447Z
20190603/eu-west-3/execute-api/aws4_request
50c80d23a5495ad30aafec2b2778675ad63d217844588482ccd10XXXXXXXXXX'
```

As per the AWS documentation, I have tried both with and without forcing url-encoding the `@` and `=` signs (so without manually encoding, `/dev/%40connections/asnFYeJtCGYCEZQ%3D`), but this does not work.

The AWS keys are correct (confirmed when using awscurl or other tools that perform the signature automatically).

This is what it looks like in Paw:
<img width="749" alt="Capture d'écran 2019-06-04 10 44 56" src="https://user-images.githubusercontent.com/7351940/58864947-f2125100-86b5-11e9-8a04-a180af3c7c3e.png">

Any clue?

**Comment by badslug** [comment] 2019-06-04 17:52
Hi,

Sorry I haven't been using AWS for a while and I'm not familiar with this API. Can you point me to the specific AWS documentation (direct link is best) so I can read up on the endpoint? My understanding is you shouldn't need to URL encode the link (Paw should do that for us - but I can verify when I test this) but since it's not working without that it's probably something in how the canonical string is being generated.

On a side note: how is the AWS Gateway WebSocket service? I was really interested in potentially using it but haven't had a chance to look at it since they announced it. I have really long lived websockets (days to weeks) and wondered how the pricing would work out since it seemed like it would be pretty expensive for really long websocket sessions. But any insights in actual usage would be really great since almost all my projects seem to be moving to websockets.

**Comment by frsechet** [comment] 2019-06-04 18:01
Hi @badslug, 

Thanks for replying quickly. The endpoint works like exactly every other endpoint, except that it has this weird `/{stage}/@connections` part which is uncommon. The documentation is still quite thin although it's been out since November 2018.

[Here is the only available documentation about it](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-how-to-call-websocket-api-connections.html), and it still misses lots of information (such as - if you want to close the connection from the server, you need to HTTP `DELETE` that particular endpoint, this appears absolutely nowhere). Other than that the process works exactly as usual, I've signed the URL using https://www.npmjs.com/package/aws-signature-v4 without any issue, pretty much like any other endpoint.

As for WS service: I don't know yet, I'm in the evaluation phase currently without any production data. It seems to work well though. However, some limitations might not be right for your use case as the max idle time is a few minutes and the max connection duration is a few hours (see https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html). Other than that it's the usual: new service so little tooling, documentation is still thin, hard to reproduce locally...

**Comment by badslug** [comment] 2019-06-06 06:05
Thanks @frsechet that should be enough for me to get started. I'll try to set up a test on my AWS account to verify and reproduce. Unfortunately I'm swamped with work stuff until probably this weekend but I'll try my best to work on it in the next few days.

**Comment by frsechet** [comment] 2019-06-06 06:15
Thanks! Absolutely no rush on my side, I have other ways to call this endpoint in the meantime 😊

**Comment by badslug** [comment] 2020-10-22 03:57
@frsechet I'm sure you didn't expect this to take over a year but I finally dusted off the extension and am going to try to address open issues (thanks to Hacktoberfest for the extra motivation). If you have the time/interest could you help with some troubleshooting? If not I'll muddle through but if you can save me from having to set up the API Gateway with WebSockets to test this it would be awesome. Thanks and apologies for the obscene amount of time it has been.

**Comment by frsechet** [comment] 2020-10-22 08:35
Hi,

Sure I'll have a go over the weekend. Is the issue currently fixed and I only have to reinstall this in pas or is there anything else I need to do to test your fix?

**Comment by badslug** [comment] 2020-10-23 03:57
Awesome. The most helpful for me is if you can, in Paw, go to Preferences > Extensions, and click the "Show Console" button. In the console, when you have your Paw request set up for the websockets API call, you should see lines with "canonical", then a text that looks HTTP-ish, and then a "string to sign" line and then another set of text. That console output should be what I need to troubleshoot the issue (in addition to the full AWS error message which I'm assuming will look just like your original post but please include the new text as it will have some new values including dates). I've attached some screenshots to hopefully clarify.
![CleanShot 2020-10-22 at 20 51 10@2x](https://user-images.githubusercontent.com/376087/96954766-f0168100-14a8-11eb-8e37-b70a26fffacc.png)
![CleanShot 2020-10-22 at 20 51 45@2x](https://user-images.githubusercontent.com/376087/96954773-f4429e80-14a8-11eb-816d-6e741e4758e8.png)
<img width="529" alt="CleanShot 2020-10-22 at 20 52 26@2x" src="https://user-images.githubusercontent.com/376087/96954782-f73d8f00-14a8-11eb-8ff1-082d719ec79a.png">

**Comment by frsechet** [comment] 2020-10-23 09:18
Here you go: 
![image](https://user-images.githubusercontent.com/7351940/96985347-fd6f5200-1520-11eb-94c3-a13e7da03f6a.png)

From the error message I receive, the canonical string is OK, but the last line of the string to sign is wrong.

**Comment by frsechet** [comment] 2020-10-23 09:24
BTW, since you asked me:

> On a side note: how is the AWS Gateway WebSocket service? I was really interested in potentially using it but haven't had a chance to look at it since they announced it. I have really long lived websockets (days to weeks) and wondered how the pricing would work out since it seemed like it would be pretty expensive for really long websocket sessions. But any insights in actual usage would be really great since almost all my projects seem to be moving to websockets.

We have had now about 1 full year of production use of this service and I can say I'm perfectly happy with it. We use it to power https://csml.dev (more precisely, the chat part of https://studio.csml.dev) and it's perfectly capable of handling millions of connections, it scales perfectly (as perfectly as lambda) and the cost is really OK so far (it's difficult to anticipate what the cost will be but with 1yr of historical data I can say that it has not been one of the main painpoints of our architecture - some backend lambdas + dynamodb have a much bigger impact than this when we get a lot of hits). The timeout of ~10 min for a ws connection might be a problem in some scenarios, but we happily reconnect and it's fine for us. Hope it helps!

**Comment by badslug** [comment] 2020-10-24 06:06
Awesome company/service. Great to hear that the Gateway WebSocket service is working out so well! I guess it makes sense that a 10 min timeout isn't really a problem in a practical way.

I have a fix checked into the `feature/websockets` branch of the repo. You can check it out using git, or if you go to the home page of this repo, select that branch in the drop down branch selector, and then click the green "code" button to get an option to download the code using a zip. To install in Paw, you'll have to uninstall the normal version of the extension, and then  you can install using `make` assuming you have it (running `make install` in the code folder). You can also manually copy the working extension into `$(HOME)/Library/Containers/com.luckymarmot.Paw/Data/Library/Application Support/com.luckymarmot.Paw/Extensions/` (note if you have Paw from Setapp then the path will look like `$(HOME)/Library/Containers/com.luckymarmot.Paw-setapp/Data/Library/Application Support/com.luckymarmot.Paw-setapp/Extensions/`).

I'm URL encoding the path for the API endpoints so if you also have other AWS APIs set up in Paw it would be great to also test those (like S3 access, etc) to make sure the change didn't break anything.

Thanks!

**Comment by frsechet** [comment] 2020-10-24 18:14
same result :(
![image](https://user-images.githubusercontent.com/7351940/97089007-123d0a00-1635-11eb-84b6-43a484748d34.png)

Basically, if you want to test locally, creating a API Gateway endpoint is quite easy (2 min), it doesn't even have to work! Then just create a AWS key that has permissions over API Gateway / execute-api, and try to sign a call to `DELETE https://YOURENDPOINT.execute-api.YOURREGION.amazonaws.com/dev/@connections/asnFYeJtCGYCEZQ=`. The last part is a valid connection ID but if it doesn't exist the encoded string should still validate (you will just get a 410 Gone error, doesn't matter).

Happy to test again if you need :-)

**Comment by badslug** [comment] 2020-10-25 03:29
Thanks! I was thinking I should just ask what’s the easiest way to test this myself - and you read my mind. 😀

I’ll ask you to verify my fix one more time - but only after I get a chance to actually call the api myself. It looks like it’s a simple encoding issue on the uri path so I don’t think it should be too hard to fix. The weirdest part is the actual canonical string they want is not the same as what you get following the documentation. They have these weird per-service exceptions to their general algorithm which is so annoying - and I guess evidence that they don’t use their own api gateway service to uniformly protect all their end points.

**Comment by badslug** [comment] 2020-10-25 04:56
@frsechet OK, it took me a while to figure out the minimum WebSocket setup API needed but once I got that set up the fix was very quick. Please try the latest commit when you have the chance. Thanks!

**Comment by frsechet** [comment] 2020-10-25 18:53
Bingo! Works like a charm 😃 
Thanks for your kind work!

**Comment by badslug** [comment] 2020-10-25 22:29
Awesome! Thanks so much for the assistance. I'll submit a 1.1.0 release to Lucky Marmot and it should show up in their extension store (and you're normal extension will get it's update).

**Closed as completed by badslug** 2020-10-25 22:29 UTC
