### ISSUE TITLE
Exception after updating to version SHA 8347b8af4932cf3e52d000163e2c6c47d18b7e7b

### ISSUE THREAD

**Issue by rhuerta** [badslug/Paw-AWSSignature4DynamicValue#14] opened 2017-04-26 17:36 UTC
JS Exception Line 214. SyntaxError: Unexpected token '{'. Expected ')' to end a 'if' condition.

**Comment by robbiehanson** [comment] 2017-04-27 00:46
I'm seeing the same error.

**Comment by JonathanMontane** [comment] 2017-04-27 07:27
@robbiehanson @rhuerta: @fmasuhr wrote PR #11 to fix this issue. If it's not merged soon, the Paw Team will probably fork the project and fix it from there.

**Comment by robbiehanson** [comment] 2017-04-27 16:02
Glad to hear there's a backup plan. Our company's PAW setup is 100% dependent on this extension.

**Comment by badslug** [comment] 2017-04-27 18:49
Hi

Sorry I'm really swamped at work and a new baby. If someone (PAW especially) would like to take over the project I'd be eternally grateful to a new maintainer. I built the extension to solve a work need but we aren't using it now so it's unfortunately become a pretty low priority.

**Comment by nglange** [comment] 2017-04-27 19:43
Congrats on the baby!  

Any chance you could accept the PR #11 in the meantime?

**Comment by badslug** [comment] 2017-04-27 23:09
Thanks! Merged. If someone can verify it works I can ping Lucky Marmot to update the PAW database.

**Comment by robbiehanson** [comment] 2017-05-01 17:14
Confirmed. I can verify this fixes JS exception crash for me.

**Comment by badslug** [comment] 2017-05-02 00:24
Thanks. I've submitted it so they can update the official Paw extensions database. I'll update the ticket when they respond.

**Comment by JonathanMontane** [comment] 2017-05-02 12:55
[Paw member here]

The latest available release (1.0.6) does not contain the code of PR #11. We will update the extension as soon as it is available.
I've also sent a suggestion to @badslug about a fix for the headers case, as the current code can raise an issue about cyclical dependencies.

**Comment by badslug** [comment] 2017-05-02 21:52
OK, merged in the cyclical dependencies code and packaged up the actual current code (rather than an old copy on my laptop... *facepalm*). Any help to test/verify would be greatly appreciated. @robbiehanson 🥇

**Comment by JonathanMontane** [comment] 2017-05-03 08:15
@badslug @rhuerta @robbiehanson @nglange the extension has been updated.

**Comment by fmasuhr** [comment] 2017-05-03 09:30
@JonathanMontane thank you for taking care. There is now another bug which was introduced by the changes. I already create a PR (https://github.com/badslug/Paw-AWSSignature4DynamicValue/pull/16) to fix this. ;)

**Comment by badslug** [comment] 2017-05-03 16:50
@fmasuhr Awesome! Thanks! Merged and released - I'm doing this really quick before I leave for the day. If you have the time to review the 1.0.8 release zip I'd appreciate it. @JonathanMontane if you can update the database it would be great since we know there is the bug in 1.0.7. Sorry everyone for my lack of testing on this.

**Comment by fmasuhr** [comment] 2017-05-03 17:06
@badslug @JonathanMontane thanks a lot. looks good to me ;)

**Comment by robbiehanson** [comment] 2017-05-03 22:59
It's working for me too. Thanks for the quick fix.

**Comment by JonathanMontane** [comment] 2017-05-04 12:00
updated!

**Comment by badslug** [comment] 2017-05-04 21:10
Everyone, thanks for all the help!

**Closed as completed by badslug** 2017-05-04 21:10 UTC
